name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd "${{ secrets.APP_DIR }}"

            echo "[*] Git sync"
            git fetch --all --prune
            git reset --hard origin/main

            echo "[*] Install deps"
            npm ci || npm install

            echo "[*] Build"
            npm run build

            echo "[*] PM2 reload/start"
            pm2 describe "${{ secrets.PM2_NAME }}" >/dev/null 2>&1 \
              && pm2 reload "${{ secrets.PM2_NAME }}" \
              || pm2 start "npm run start" --name "${{ secrets.PM2_NAME }}" --cwd "${{ secrets.APP_DIR }}" --time

            pm2 save
            echo "✅ Deploy done."

